# -*- coding: utf-8 -*-
"""ravdess-tess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQjPiAMrAEXDZuE918lbOBNbciRJqyTT
"""

import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
import librosa
import librosa.display
from IPython.display import Audio

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd

# Initialize lists
paths = []
labels = []

# Define dataset directory (CHANGE THIS PATH IF NEEDED)
dataset_path = "E:/Space 1/Minor Project/VS/ravdess+tess/"

# RAVDESS Emotion Mapping (based on filenames)
ravdess_emotion_map = {
    '01': 'neutral',
    '02': 'calm',
    '03': 'happy',
    '04': 'sad',
    '05': 'angry',
    '06': 'fearful',  # Ensure consistency
    '07': 'disgust',
    '08': 'surprised'
}

# TESS Emotion Mapping (Fixing 'pleasant_surprise' issue)
tess_emotion_map = {
    "pleasant_surprise": "surprised",
    "ps": "surprised",  # Just in case "ps" appears
    "fear": "fearful"  # Unifying 'fear' from TESS with 'fearful' from RAVDESS
}

# Load RAVDESS Dataset
ravdess_path = os.path.join(dataset_path, "audio_speech_actors_01-24")
for dirname, _, filenames in os.walk(ravdess_path):
    for filename in filenames:
        if filename.endswith('.wav'):
            paths.append(os.path.join(dirname, filename))
            emotion_code = filename.split('-')[2]  # Extract emotion code
            labels.append(ravdess_emotion_map.get(emotion_code, "unknown"))  # Map emotion

# Load TESS Dataset
tess_path = os.path.join(dataset_path, "TESS Toronto emotional speech set data")
for dirname, _, filenames in os.walk(tess_path):
    for filename in filenames:
        if filename.endswith('.wav'):
            paths.append(os.path.join(dirname, filename))
            emotion = filename.split('_')[-1].split('.')[0].lower()  # Extract emotion

            # Apply mapping
            emotion = tess_emotion_map.get(emotion, emotion)  # Fix "ps" & "fear"

            labels.append(emotion)

# Create DataFrame
df = pd.DataFrame({'file_path': paths, 'label': labels})

# Print dataset info
print(f"✅ Dataset Loaded: {len(df)} files")
print(df['label'].value_counts())  # Check label distribution

print(set(labels))  # Show all unique emotion labels

len(paths)

paths[:10]

labels[:10]

print(df.columns)

## Create a dataframe
df = pd.DataFrame()
df['speech'] = paths
df['label'] = labels
df.head()

sns.countplot(data=df, x='label')

""" Oversampling (Adding More Samples for Underrepresented Emotions)"""

from sklearn.utils import resample

# Find the maximum number of samples per emotion
max_count = df['label'].value_counts().max()

# Balance dataset by oversampling
df_balanced = df.groupby('label', group_keys=False).apply(lambda x: resample(x, replace=True, n_samples=max_count))

# Shuffle dataset
df_balanced = df_balanced.sample(frac=1).reset_index(drop=True)

# Check new distribution
print(df_balanced['label'].value_counts())

# Plot new distribution
plt.figure(figsize=(10, 5))
sns.countplot(data=df_balanced, x='label', palette='viridis')
plt.xticks(rotation=45)
plt.title("Balanced Emotion Distribution (Oversampling)")
plt.show()

def waveplot(data, sr, emotion):
    """Plots the waveform of the given audio sample."""
    plt.figure(figsize=(10, 4))
    plt.title(f"Waveform - {emotion}", size=20)
    librosa.display.waveshow(data, sr=sr)  # If using older librosa, change to waveplot()
    plt.xlabel("Time (s)")
    plt.ylabel("Amplitude")
    plt.show()

def spectrogram(data, sr, emotion):
    """Plots the spectrogram of the given audio sample."""
    x = librosa.stft(data, n_fft=2048, hop_length=512)  # Standard STFT settings
    xdb = librosa.amplitude_to_db(abs(x))  # Convert to decibels

    plt.figure(figsize=(11, 4))
    plt.title(f"Spectrogram - {emotion}", size=20)
    librosa.display.specshow(xdb, sr=sr, x_axis='time', y_axis='hz')
    plt.colorbar(format='%+2.0f dB')
    plt.xlabel("Time (s)")
    plt.ylabel("Frequency (Hz)")
    # plt.show()

emotion = 'happy'
path = np.array(df['speech'][df['label']==emotion])[0]
data, sampling_rate = librosa.load(path)
waveplot(data, sampling_rate, emotion)
spectrogram(data, sampling_rate, emotion)
Audio(path)

emotion = 'sad'
path = np.array(df['speech'][df['label']==emotion])[0]
data, sampling_rate = librosa.load(path)
waveplot(data, sampling_rate, emotion)
spectrogram(data, sampling_rate, emotion)
Audio(path)

emotion = 'calm'
path = np.array(df['speech'][df['label']==emotion])[0]
data, sampling_rate = librosa.load(path)
waveplot(data, sampling_rate, emotion)
spectrogram(data, sampling_rate, emotion)
Audio(path)

"""Extracting Features

MFCC
"""

def extract_mfcc(filename):
    y, sr = librosa.load(filename, duration=3, offset=0.5)
    mfcc = np.mean(librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40).T, axis=0)
    return mfcc

extract_mfcc(df['speech'][0])
#  Extract MFCC for a Single File

X_mfcc = df['speech'].apply(lambda x: extract_mfcc(x)) #Extract MFCC for All Files

X_mfcc

print(X_mfcc.shape)  # Should be (num_samples,)  #Check the output shape:
print(X_mfcc.iloc[0].shape)  # Should be (40,)

#Convert to a NumPy Array (For ML Models)

X = np.array(X_mfcc.tolist())  # Convert Series of arrays to a NumPy array
print(X.shape)  # Expected: (num_samples, 40)

"""Other Features"""

import librosa
import numpy as np

def extract_features(filename):
    y, sr = librosa.load(filename, duration=3, offset=0.5)

    # MFCC (Mel-frequency cepstral coefficients)
    mfcc = np.mean(librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40).T, axis=0)

    # Chroma Features (Captures harmonic and tonal information)
    chroma = np.mean(librosa.feature.chroma_stft(y=y, sr=sr).T, axis=0)

    # Spectral Contrast (Difference between peaks and valleys in a spectrum)
    contrast = np.mean(librosa.feature.spectral_contrast(y=y, sr=sr).T, axis=0)

    # Zero-Crossing Rate (ZCR - Measures signal noisiness)
    zcr = np.mean(librosa.feature.zero_crossing_rate(y).T, axis=0)

    # Root Mean Square Energy (RMSE - Measures loudness)
    rmse = np.mean(librosa.feature.rms(y=y).T, axis=0)

    # Combine all extracted features into a single feature vector
    features = np.hstack([mfcc, chroma, contrast, zcr, rmse])

    return features

X_features = df['speech'].apply(lambda x: extract_features(x))  # Extract features
X = np.array(X_features.tolist())  # Convert to NumPy array

print(X.shape)  # Expected shape: (7040, number_of_features)

"""Label encoding"""

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
y = encoder.fit_transform(df[['label']]).toarray()  # Convert labels to One-Hot Vectors
print(y.shape)  # Should be (7040, number_of_classes)

"""Train/Test Split"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

"""Scaling of the features"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""Import required libraries"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

"""Train the Random Forest Model"""

# Train a Random Forest Classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, np.argmax(y_train, axis=1))  # Convert one-hot labels to categorical labels

# Predictions
y_pred_rf = rf_model.predict(X_test)

# Accuracy
rf_accuracy = accuracy_score(np.argmax(y_test, axis=1), y_pred_rf)
print(f"Random Forest Accuracy: {rf_accuracy:.2f}")

# Train an SVM Classifier
svm_model = SVC(kernel='rbf', probability=True)  # RBF kernel works well for classification
svm_model.fit(X_train, np.argmax(y_train, axis=1))

# Predictions
y_pred_svm = svm_model.predict(X_test)

# Accuracy
svm_accuracy = accuracy_score(np.argmax(y_test, axis=1), y_pred_svm)
print(f"SVM Accuracy: {svm_accuracy:.2f}")

def plot_confusion_matrix(y_true, y_pred, model_name):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8,6))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=encoder.categories_[0], yticklabels=encoder.categories_[0])
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")
    plt.title(f"Confusion Matrix - {model_name}")
    plt.show()

# Confusion Matrix for Random Forest
plot_confusion_matrix(np.argmax(y_test, axis=1), y_pred_rf, "Random Forest")

# Confusion Matrix for SVM
plot_confusion_matrix(np.argmax(y_test, axis=1), y_pred_svm, "SVM")

# Classification Report for Random Forest
print("Random Forest Classification Report:\n", classification_report(np.argmax(y_test, axis=1), y_pred_rf))

# Classification Report for SVM
print("SVM Classification Report:\n", classification_report(np.argmax(y_test, axis=1), y_pred_svm))

from sklearn.linear_model import LogisticRegression

# Train Logistic Regression
log_reg_model = LogisticRegression(max_iter=1000)
log_reg_model.fit(X_train, np.argmax(y_train, axis=1))

# Predict
y_pred_log = log_reg_model.predict(X_test)

# Evaluate
print("Logistic Regression Accuracy:", accuracy_score(np.argmax(y_test, axis=1), y_pred_log))
print(classification_report(np.argmax(y_test, axis=1), y_pred_log, target_names=encoder.categories_[0]))

# Confusion Matrix
cm_log = confusion_matrix(np.argmax(y_test, axis=1), y_pred_log)
plt.figure(figsize=(8,6))
sns.heatmap(cm_log, annot=True, fmt="d", cmap="Blues", xticklabels=encoder.categories_[0], yticklabels=encoder.categories_[0])
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Logistic Regression Confusion Matrix")
plt.show()

import matplotlib.pyplot as plt

# Store model names and their respective accuracies
models = ["Random Forest", "SVM", "Logistic Regression"]
accuracies = [accuracy_score(np.argmax(y_test, axis=1), y_pred_rf),
              accuracy_score(np.argmax(y_test, axis=1), y_pred_svm),
              accuracy_score(np.argmax(y_test, axis=1), y_pred_log)]

# Plot accuracy comparison
plt.figure(figsize=(8, 5))
plt.bar(models, accuracies, color=['blue', 'green', 'orange'])
plt.ylim(0, 1)  # Accuracy range is between 0 and 1
plt.ylabel("Accuracy")
plt.xlabel("Models")
plt.title("Model Accuracy Comparison")

# Show accuracy values on bars
for i, acc in enumerate(accuracies):
    plt.text(i, acc + 0.02, f"{acc:.4f}", ha='center', fontsize=12)

plt.show()

"""Reshaping data for CNN and LSTM"""

# Reshape for CNN
X_cnn = X.reshape(X.shape[0], X.shape[1], 1)

# Reshape for LSTM (treat each feature as a timestep)
X_lstm = X.reshape(X.shape[0], X.shape[1], 1)

"""Building the CNN Model"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout

cnn_model = Sequential([
    Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_cnn.shape[1], 1)),
    MaxPooling1D(pool_size=2),
    Conv1D(128, kernel_size=3, activation='relu'),
    MaxPooling1D(pool_size=2),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(y.shape[1], activation='softmax')  # Output layer with softmax activation
])

cnn_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train CNN
cnn_model.fit(X_cnn, y, epochs=30, batch_size=32, validation_split=0.2)

"""Building the LSTM Models"""

from tensorflow.keras.layers import LSTM, Bidirectional

lstm_model = Sequential([
    LSTM(128, return_sequences=True, input_shape=(X_lstm.shape[1], 1)),
    LSTM(64),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(y.shape[1], activation='softmax')
])

lstm_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train LSTM
lstm_model.fit(X_lstm, y, epochs=30, batch_size=32, validation_split=0.2)

"""Train cnn"""

cnn_model.fit(X_cnn, y, epochs=20, batch_size=32, validation_split=0.2)

"""Evaluate cnn on test set"""

# Reshape test data for CNN
X_cnn_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

# Now, evaluate the model
cnn_test_loss, cnn_test_acc = cnn_model.evaluate(X_cnn_test, y_test)
print(f"CNN Test Accuracy: {cnn_test_acc:.2f}")

lstm_model.fit(X_lstm, y, epochs=20, batch_size=32, validation_split=0.2)

# Reshape test data for LSTM
X_lstm_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

# Evaluate LSTM
lstm_test_loss, lstm_test_acc = lstm_model.evaluate(X_lstm_test, y_test)
print(f"LSTM Test Accuracy: {lstm_test_acc:.2f}")

print(pd.Series(np.argmax(y_train, axis=1)).value_counts())
print(pd.Series(np.argmax(y_test, axis=1)).value_counts())

from sklearn.utils import resample

# Find max class count
max_count = df['label'].value_counts().max()

# Oversample minority classes
df_balanced = df.groupby('label', group_keys=False).apply(lambda x: resample(x, replace=True, n_samples=max_count))

# Shuffle dataset
df_balanced = df_balanced.sample(frac=1).reset_index(drop=True)

# Check new distribution
print(df_balanced['label'].value_counts())

from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_balanced, y_balanced = smote.fit_resample(X, np.argmax(y, axis=1))

# Convert labels back to one-hot encoding
y_balanced = np.eye(y.shape[1])[y_balanced]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_balanced, y_balanced, test_size=0.2, random_state=42)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)  # Should be more balanced now

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""Reshape Data for CNN and LSTM

CNN expects (samples, features, 1)

LSTM expects (samples, time steps, features)
"""

# Reshape for CNN
X_cnn_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_cnn_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

# Reshape for LSTM
X_lstm_train = X_train.reshape(X_train.shape[0], 1, X_train.shape[1])
X_lstm_test = X_test.reshape(X_test.shape[0], 1, X_test.shape[1])

"""Train a Better CNN Model"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, BatchNormalization

cnn_model = Sequential([
    Conv1D(128, kernel_size=5, activation='relu', input_shape=(X_cnn_train.shape[1], 1)),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),
    Dropout(0.3),

    Conv1D(256, kernel_size=5, activation='relu'),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),
    Dropout(0.3),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.4),
    Dense(y_train.shape[1], activation='softmax')  # Output layer for multi-class classification
])

cnn_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
cnn_model.summary()

# Train CNN
cnn_model.fit(X_cnn_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

"""Train a Better LSTM Model"""

from tensorflow.keras.layers import LSTM

lstm_model = Sequential([
    LSTM(128, return_sequences=True, input_shape=(1, X_lstm_train.shape[2])),
    Dropout(0.3),
    LSTM(128, return_sequences=False),
    Dense(128, activation='relu'),
    Dropout(0.4),
    Dense(y_train.shape[1], activation='softmax')
])

lstm_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
lstm_model.summary()

# Train LSTM
lstm_model.fit(X_lstm_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

"""Evaluate CNN & LSTM on Test Data"""

# Evaluate CNN
cnn_test_loss, cnn_test_acc = cnn_model.evaluate(X_cnn_test, y_test)
print(f"CNN Test Accuracy: {cnn_test_acc:.2f}")

# Evaluate LSTM
lstm_test_loss, lstm_test_acc = lstm_model.evaluate(X_lstm_test, y_test)
print(f"LSTM Test Accuracy: {lstm_test_acc:.2f}")

"""Check Confusion Matrix for Misclassifications"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# CNN Confusion Matrix
y_pred_cnn = cnn_model.predict(X_cnn_test)
cm_cnn = confusion_matrix(np.argmax(y_test, axis=1), np.argmax(y_pred_cnn, axis=1))

plt.figure(figsize=(8,6))
sns.heatmap(cm_cnn, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - CNN")
plt.show()

# LSTM Confusion Matrix
y_pred_lstm = lstm_model.predict(X_lstm_test)
cm_lstm = confusion_matrix(np.argmax(y_test, axis=1), np.argmax(y_pred_lstm, axis=1))

plt.figure(figsize=(8,6))
sns.heatmap(cm_lstm, annot=True, fmt="d", cmap="Reds")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - LSTM")
plt.show()

from sklearn.metrics import classification_report

y_pred_cnn = np.argmax(cnn_model.predict(X_cnn_test), axis=1)
y_pred_lstm = np.argmax(lstm_model.predict(X_lstm_test), axis=1)

y_true = np.argmax(y_test, axis=1)

print("📌 CNN Classification Report")
print(classification_report(y_true, y_pred_cnn))

print("\n📌 LSTM Classification Report")
print(classification_report(y_true, y_pred_lstm))

"""CNN vs LSTM visualization"""

history_cnn = cnn_model.fit(X_cnn_train, y_train, epochs=50, batch_size=32, validation_split=0.2)
history_lstm = lstm_model.fit(X_lstm_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

"""HyperParametr Tuning"""

HyperParametr Tuning

"""Hyper Parameter Tuning for Random Forest"""

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# Define hyperparameter grid
param_grid_rf = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Initialize Random Forest model
rf = RandomForestClassifier(random_state=42)

# Perform GridSearchCV
grid_rf = GridSearchCV(rf, param_grid_rf, cv=5, scoring='accuracy', n_jobs=-1, verbose=2)
grid_rf.fit(X_train, np.argmax(y_train, axis=1))

# Best parameters
print("Best Random Forest Parameters:", grid_rf.best_params_)

# Best model
best_rf = grid_rf.best_estimator_

# Evaluate on test data
y_pred_rf = best_rf.predict(X_test)
print("Tuned RF Accuracy:", accuracy_score(np.argmax(y_test, axis=1), y_pred_rf))

"""HyperParamter Tuning for SVM"""

from sklearn.svm import SVC

# Define hyperparameter grid
param_grid_svm = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto']
}

# Initialize SVM model
svm = SVC()

# Perform GridSearchCV
grid_svm = GridSearchCV(svm, param_grid_svm, cv=5, scoring='accuracy', n_jobs=-1, verbose=2)
grid_svm.fit(X_train, np.argmax(y_train, axis=1))

# Best parameters
print("Best SVM Parameters:", grid_svm.best_params_)

# Best model
best_svm = grid_svm.best_estimator_

# Evaluate on test data
y_pred_svm = best_svm.predict(X_test)
print("Tuned SVM Accuracy:", accuracy_score(np.argmax(y_test, axis=1), y_pred_svm))

"""HyperParameter Tuning for Logistic Regression"""

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Logistic Regression with more iterations
lr = LogisticRegression(max_iter=1000, solver='saga')
lr.fit(X_train_scaled, np.argmax(y_train, axis=1))

# Predictions
y_pred_lr = lr.predict(X_test_scaled)

# Evaluate
accuracy_lr = accuracy_score(np.argmax(y_test, axis=1), y_pred_lr)
print(f"Logistic Regression Accuracy: {accuracy_lr:.4f}")

"""Apply PCA for Dimensionality Reduction"""

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Standardize features before PCA
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply PCA (retain 95% variance)
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X_scaled)

print(f"Original Shape: {X.shape}")
print(f"Reduced Shape after PCA: {X_pca.shape}")

"""Perform Data Augmentation"""

import librosa
import numpy as np

# Function to add noise
def add_noise(y, noise_level=0.005):
    noise = noise_level * np.random.randn(len(y))
    return y + noise

# Function for time-stretching
def time_stretch(y, rate=1.1):
    return librosa.effects.time_stretch(y, rate=rate) if len(y) > 1 else y

# Function for pitch shifting
def pitch_shift(y, sr, n_steps=2):
    return librosa.effects.pitch_shift(y.astype(np.float32), sr=sr, n_steps=n_steps) if len(y) > 1 else y

# Function to extract features (EXACTLY 61 features)
def extract_features(y, sr):
    """
    Extracts features ensuring EXACTLY 61 features to match original data.
    """
    # Extract 30 MFCCs
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=30)
    mfcc_mean = np.mean(mfcc.T, axis=0)

    # Compute delta MFCCs (first-order derivative)
    delta_mfcc = librosa.feature.delta(mfcc)
    delta_mfcc_mean = np.mean(delta_mfcc.T, axis=0)

    # Compute delta-delta MFCCs (second-order derivative)
    delta2_mfcc = librosa.feature.delta(mfcc, order=2)
    delta2_mfcc_mean = np.mean(delta2_mfcc.T, axis=0)

    # Additional Features
    chroma = np.mean(librosa.feature.chroma_stft(y=y, sr=sr).T, axis=0)
    contrast = np.mean(librosa.feature.spectral_contrast(y=y, sr=sr).T, axis=0)
    zcr = np.mean(librosa.feature.zero_crossing_rate(y).T, axis=0)
    rmse = np.mean(librosa.feature.rms(y=y).T, axis=0)

    # Combine features EXACTLY matching 61
    feature_vector = np.hstack([
        mfcc_mean,          # 30 features
        delta_mfcc_mean,    # 30 features of delta
        chroma,             # Likely 12 features
        contrast,           # Specific to spectral contrast
        zcr,                # Zero crossing rate
        rmse                # Root Mean Square Energy
    ])

    # Ensure exactly 61 features
    feature_vector = feature_vector[:61]

    print(f"Feature Vector Length: {len(feature_vector)}")

    return feature_vector

# Function to apply augmentation to the entire dataset
def augment_data(df, max_augmentations=3):
    augmented_data = []
    labels = []

    for i, path in enumerate(df['speech']):
        print(f"Processing {i+1}/{len(df)}", end='\r')

        try:
            y, sr = librosa.load(path, duration=3, offset=0.5, mono=True)

            # Original features
            original_features = extract_features(y, sr)
            augmented_data.append(original_features)
            labels.append(df['label'].iloc[i])

            # Augmentations
            augmentations = [
                add_noise(y),
                time_stretch(y, rate=1.1),
                pitch_shift(y, sr, n_steps=2)
            ]

            # Limit augmentations
            for aug in augmentations[:max_augmentations]:
                aug_features = extract_features(aug, sr)
                augmented_data.append(aug_features)
                labels.append(df['label'].iloc[i])

        except Exception as e:
            print(f"\nError processing file {path}: {e}")
            continue

    return np.array(augmented_data), np.array(labels)

# Apply Augmentation with error handling
try:
    X_aug, y_aug = augment_data(df)
    print(f"\nOriginal Data Shape: {X_train.shape}")
    print(f"Augmented Data Shape: {X_aug.shape}")

    # Verify feature vector length
    assert X_aug.shape[1] == 61, f"Expected 61 features, got {X_aug.shape[1]}"

except Exception as e:
    print(f"Augmentation error: {e}")

"""Check Variance Retained by PCA"""

import matplotlib.pyplot as plt
import numpy as np

# Explained variance ratio
explained_variance = np.cumsum(pca.explained_variance_ratio_)

# Plot
plt.figure(figsize=(8,5))
plt.plot(range(1, len(explained_variance)+1), explained_variance, marker='o', linestyle='--')
plt.xlabel('Number of Principal Components')
plt.ylabel('Cumulative Explained Variance')
plt.title('Explained Variance by PCA Components')
plt.grid()
plt.show()

# ✅ Apply augmentation to your dataset
X_aug, y_aug = augment_data(df)

print(f"Augmented Features Shape: {X_aug.shape}")
print(f"Augmented Labels Shape: {y_aug.shape}")

"""Apply PCA on Both Original & Augmented Data"""

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# ✅ Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)  # Fit on original data
X_aug_scaled = scaler.transform(X_aug)  # Transform augmented data

# ✅ Apply PCA (Retain 95% variance)
pca = PCA(n_components=0.95)
X_train_pca = pca.fit_transform(X_train_scaled)  # Fit on original data
X_aug_pca = pca.transform(X_aug_scaled)  # Transform augmented data

# ✅ Print shapes
print(f"Original PCA Shape: {X_train_pca.shape}")
print(f"Augmented PCA Shape: {X_aug_pca.shape}")

print(f"X_train Shape: {X_train.shape}")  # Shape before PCA
print(f"X_aug Shape: {X_aug.shape}")      # Shape before PCA

print(f"y_train shape: {y_train.shape}")
print(f"y_aug shape: {y_aug.shape}")

"""label encoding"""

import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

def encode_labels(y_train, y_aug, default_label='neutral'):
    # Convert one-hot encoded training labels
    if len(y_train.shape) == 2 and y_train.shape[1] > 1:
        # If already one-hot encoded, this preserves the original encoding
        y_train_labels = y_train

        # Verify it's actually a one-hot encoded matrix
        if not np.all(np.sum(y_train_labels, axis=1) == 1):
            raise ValueError("Input does not appear to be a valid one-hot encoded matrix")

        # Derive class names from column indices
        class_names = [str(i) for i in range(y_train_labels.shape[1])]
    else:
        raise ValueError("Training labels must be a one-hot encoded matrix")

    # Handle augmented labels
    y_aug_encoded = np.zeros((len(y_aug), len(class_names)))

    # If 'neutral' is in y_aug, distribute it across classes
    if np.any(y_aug == default_label):
        # Count 'neutral' instances
        neutral_count = np.sum(y_aug == default_label)

        # Simple distribution: equal probability across classes
        neutral_distribution = np.ones(len(class_names)) / len(class_names)

        # Repeat the distribution for each neutral instance
        y_aug_encoded[y_aug == default_label] = neutral_distribution

    # Combine datasets
    y_final = np.vstack((y_train_labels, y_aug_encoded))

    # Debugging output
    print("✅ Training labels shape:", y_train_labels.shape)
    print("✅ Augmented labels shape:", y_aug_encoded.shape)
    print("✅ Final encoded shape:", y_final.shape)
    print("✅ Unique classes:", class_names)

    return y_final

y_final = encode_labels(y_train, y_aug)
X_final = np.vstack((X_train, X_aug))

# ✅ Encode Labels BEFORE PCA
y_final = encode_labels(y_train, y_aug)

# ✅ Merge features
X_combined = np.vstack((X_train, X_aug))

# ✅ Standardization
scaler = StandardScaler()
X_combined_scaled = scaler.fit_transform(X_combined)

# ✅ Apply PCA on combined data
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X_combined_scaled)

# ✅ Train-Test Split
X_train_pca, X_test_pca, y_train_final, y_test_final = train_test_split(
    X_pca, y_final, test_size=0.2, stratify=y_final, random_state=42
)

# ✅ Retrain ML Models
best_rf.fit(X_train_pca, np.argmax(y_train_final, axis=1))
y_pred_rf = best_rf.predict(X_test_pca)
print("Updated RF Accuracy:", accuracy_score(np.argmax(y_test_final, axis=1), y_pred_rf))

import numpy as np

# Define class mapping (update this according to your dataset)
label_mapping = {
    "neutral": 0,
    "happy": 1,
    "sad": 2,
    "angry": 3,
    "fearful": 4,
    "disgusted": 5,
    "surprised": 6,
    "calm": 7
}

# Reverse mapping (if needed)
reverse_label_mapping = {v: k for k, v in label_mapping.items()}

def encode_labels(y_train, y_aug):
    # Convert y_aug to a NumPy array
    y_aug = np.array(y_aug)

    # Check if y_aug contains numeric or string labels
    if np.issubdtype(y_aug.dtype, np.number):
        # If already numeric, use as is
        y_aug_numeric = y_aug
    else:
        # If string labels, map them to numeric
        y_aug_numeric = np.array([label_mapping[label] for label in y_aug])

    # One-hot encode y_aug
    y_aug_onehot = np.eye(8)[y_aug_numeric]

    # Stack the one-hot encoded arrays
    y_final = np.vstack((y_train, y_aug_onehot))

    print("✅ Training labels shape:", y_train.shape)
    print("✅ Augmented labels shape:", y_aug_onehot.shape)
    print("✅ Final encoded shape:", y_final.shape)
    print("✅ Unique numeric labels in y_train:", np.unique(np.argmax(y_train, axis=1)))
    print("✅ Unique numeric labels in y_aug:", np.unique(y_aug_numeric))

    return y_final

# Run the encoding
y_final = encode_labels(y_train, y_aug)

print("🔎 Features shape:", X.shape)      # Should match labels
print("🔎 Labels shape:", y_final.shape) # Should match features

# Ensure both X and y_final have the same number of samples
min_samples = min(X.shape[0], y_final.shape[0])
X = X[:min_samples]
y_final = y_final[:min_samples]

print("✅ Adjusted Features shape:", X.shape)
print("✅ Adjusted Labels shape:", y_final.shape)

from sklearn.model_selection import train_test_split

# Split into training and testing sets (80-20 split)
X_train, X_test, y_train, y_test = train_test_split(
    X, y_final, test_size=0.2, random_state=42, stratify=y_final
)

print("✅ Training data shape:", X_train.shape, y_train.shape)
print("✅ Test data shape:", X_test.shape, y_test.shape)